spring:
  application:
    name: moodly
  profiles:
    default: local
  data:
    mongodb:
      auto-index-creation: true
  elasticsearch:
    uris: http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}

moodly:

  entries:
    collection-name: ${MOODLY_ENTRIES_COLLECTION_NAME}

  cdc:
    enabled: ${MOODLY_CDC_ENABLED}
    stream-id: ${MOODLY_CDC_STREAM_ID}
    maintenance-key: ${MOODLY_CDC_MAINTENANCE_KEY}
    retry:
      max-attempts: ${MOODLY_CDC_RETRY_MAX_ATTEMPTS}
      initial-backoff-ms: ${MOODLY_CDC_RETRY_INITIAL_BACKOFF_MS}
    reindex:
      batch-size: ${MOODLY_CDC_REINDEX_BATCH_SIZE}

  search:
    index:
      name: ${MOODLY_SEARCH_INDEX_NAME}
      mapping-resource: ${MOODLY_SEARCH_INDEX_MAPPING_RESOURCE}
      initialization-enabled: ${MOODLY_SEARCH_INDEX_INITIALIZATION_ENABLED}

management:
  endpoint:
    health:
      show-components: when_authorized
      show-details: when_authorized
