spring:
  mongodb:
    uri: mongodb://${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DATABASE}?replicaSet=${MONGODB_REPLICA_SET}

moodly:
  cdc:
    enabled: ${MOODLY_CDC_ENABLED}
  search:
    index:
      initialization-enabled: ${MOODLY_SEARCH_INDEX_INITIALIZATION_ENABLED}
