spring:
  application:
    name: moodly
  profiles:
    default: local
  data:
    mongodb:
      auto-index-creation: true
  elasticsearch:
    uris: ${ELASTICSEARCH_URI:http://localhost:9200}

moodly:
  search:
    index:
      initialization-enabled: true
