spring:
  mongodb:
    uri: mongodb://${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DATABASE}?replicaSet=${MONGODB_REPLICA_SET}

management:
  endpoint:
    health:
      show-components: always
      show-details: always
